### ISSUE TITLE
problem after send post

### ISSUE THREAD

**Issue by shm379** [QomOSC/blog#2]
hi i signup to site and try to send a post after click to submit button i received this massage 
`{"type":2}`

please fix! and thank you for beautiful design .

**Comment by matinkaboli** [comment]
I'm sorry, but right now you MUST add an image for the post. If you don't, then you'll receive an error.
We'll fix that later and THANK YOU for giving us feednback :)

**Comment by shm379** [comment]
![2018-02-09_0-16-06](https://user-images.githubusercontent.com/17412223/35997387-9191a562-0d2e-11e8-8058-2bba7c33bd98.png)
